# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 05 Aug 2022 12:09:25 +0000
*               @ALL          1
*               @user         8
