<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Fri, 05 Aug 2022 12:09:25 +0000
 */
$conf['title'] = 'WikiAtik';
$conf['lang'] = 'en';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
