# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 04 Aug 2022 14:31:02 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

superadmin:$2y$10$yvTztdd48KSfovXgnLP8Zelia6BZrZgmyXlt0qY.sq5/ReGw0F.Oi:SuperAdmin Atik:sviluppo@atik.it:admin,user
