# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 05 Aug 2022 12:09:25 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

superadmin:$2y$10$Xtr6EgRXlqtlOYUmpCo7nOSIqUAt.m97sULJ5rhuiuM394eHqBn2C:SuperAdmin Atik:sviluppo@atik.it:admin,user
